#############################################################################
# Makefile for building zautempo
# Generated by tmake at 23:26, 2002/10/09
#     Project: zautempo
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	arm-linux-gcc
CXX	=	arm-linux-g++
CFLAGS	=	-pipe -Wall -W -O2 -DNO_DEBUG
CXXFLAGS=	-pipe -DQT_QWS_EBX -DQT_QWS_CUSTOM -DQWS -fno-exceptions -fno-rtti -Wall -W -O2 -DNO_DEBUG
INCPATH	=	-I$(QPEDIR)/include -I$(QTDIR)/include
LINK	=	arm-linux-gcc
LFLAGS	=	
LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -lqpe -lqte
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	qtprojectdialog.h
SOURCES =	main.cpp \
		qtprojectdialog.cpp
OBJECTS =	main.o \
		qtprojectdialog.o \
		qtprojectdialogbase.o
INTERFACES =	qtprojectdialogbase.ui
UICDECLS =	qtprojectdialogbase.h
UICIMPLS =	qtprojectdialogbase.cpp
SRCMOC	=	moc_qtprojectdialog.cpp \
		moc_qtprojectdialogbase.cpp
OBJMOC	=	moc_qtprojectdialog.o \
		moc_qtprojectdialogbase.o
DIST	=	
TARGET	=	zautempo
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake:
	tmake zautempo.pro

dist:
	$(TAR) zautempo.tar zautempo.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) zautempo.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

main.o: main.cpp \
		/opt/Qtopia/sharp/include/qpe/qpeapplication.h \
		/opt/Qtopia/sharp/include/qapplication.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qasciidict.h \
		/opt/Qtopia/sharp/include/qgdict.h \
		/opt/Qtopia/sharp/include/qtranslator.h \
		/opt/Qtopia/sharp/include/qintdict.h \
		qtprojectdialog.h \
		qtprojectdialogbase.h \
		/opt/Qtopia/sharp/include/qvariant.h \
		/opt/Qtopia/sharp/include/qmap.h

qtprojectdialog.o: qtprojectdialog.cpp \
		./sharp_char.h \
		qtprojectdialog.h \
		qtprojectdialogbase.h \
		/opt/Qtopia/sharp/include/qvariant.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h \
		/opt/Qtopia/sharp/include/qpushbutton.h \
		/opt/Qtopia/sharp/include/qbutton.h \
		/opt/Qtopia/sharp/include/qiconset.h \
		/opt/Qtopia/sharp/include/qpixmap.h \
		/opt/Qtopia/sharp/include/qlabel.h \
		/opt/Qtopia/sharp/include/qframe.h \
		/opt/Qtopia/sharp/include/qtimer.h \
		/opt/Qtopia/sharp/include/qlcdnumber.h \
		/opt/Qtopia/sharp/include/qbitarray.h \
		/opt/Qtopia/sharp/include/qprogressbar.h \
		/opt/Qtopia/sharp/include/qradiobutton.h \
		/opt/Qtopia/sharp/include/qcombobox.h \
		/opt/Qtopia/sharp/include/qlineedit.h \
		sharp_char.h

qtprojectdialogbase.h: qtprojectdialogbase.ui
	$(UIC) qtprojectdialogbase.ui -o $(INTERFACE_DECL_PATH)/qtprojectdialogbase.h

qtprojectdialogbase.cpp: qtprojectdialogbase.ui
	$(UIC) qtprojectdialogbase.ui -i qtprojectdialogbase.h -o qtprojectdialogbase.cpp

qtprojectdialogbase.o: qtprojectdialogbase.cpp \
		qtprojectdialogbase.h \
		qtprojectdialogbase.ui

moc_qtprojectdialog.o: moc_qtprojectdialog.cpp \
		qtprojectdialog.h \
		qtprojectdialogbase.h \
		/opt/Qtopia/sharp/include/qvariant.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

moc_qtprojectdialogbase.o: moc_qtprojectdialogbase.cpp \
		qtprojectdialogbase.h \
		/opt/Qtopia/sharp/include/qvariant.h \
		/opt/Qtopia/sharp/include/qstring.h \
		/opt/Qtopia/sharp/include/qcstring.h \
		/opt/Qtopia/sharp/include/qarray.h \
		/opt/Qtopia/sharp/include/qgarray.h \
		/opt/Qtopia/sharp/include/qshared.h \
		/opt/Qtopia/sharp/include/qglobal.h \
		/opt/Qtopia/sharp/include/qfeatures.h \
		/opt/Qtopia/sharp/include/qconfig.h \
		/opt/Qtopia/sharp/include/qvaluelist.h \
		/opt/Qtopia/sharp/include/qdatastream.h \
		/opt/Qtopia/sharp/include/qiodevice.h \
		/opt/Qtopia/sharp/include/qstringlist.h \
		/opt/Qtopia/sharp/include/qregexp.h \
		/opt/Qtopia/sharp/include/qmap.h \
		/opt/Qtopia/sharp/include/qwidget.h \
		/opt/Qtopia/sharp/include/qwindowdefs.h \
		/opt/Qtopia/sharp/include/qobjectdefs.h \
		/opt/Qtopia/sharp/include/qnamespace.h \
		/opt/Qtopia/sharp/include/qobject.h \
		/opt/Qtopia/sharp/include/qevent.h \
		/opt/Qtopia/sharp/include/qregion.h \
		/opt/Qtopia/sharp/include/qrect.h \
		/opt/Qtopia/sharp/include/qsize.h \
		/opt/Qtopia/sharp/include/qpoint.h \
		/opt/Qtopia/sharp/include/qmime.h \
		/opt/Qtopia/sharp/include/qlist.h \
		/opt/Qtopia/sharp/include/qglist.h \
		/opt/Qtopia/sharp/include/qcollection.h \
		/opt/Qtopia/sharp/include/qpaintdevice.h \
		/opt/Qtopia/sharp/include/qpalette.h \
		/opt/Qtopia/sharp/include/qcolor.h \
		/opt/Qtopia/sharp/include/qbrush.h \
		/opt/Qtopia/sharp/include/qcursor.h \
		/opt/Qtopia/sharp/include/qfont.h \
		/opt/Qtopia/sharp/include/qfontmetrics.h \
		/opt/Qtopia/sharp/include/qfontinfo.h \
		/opt/Qtopia/sharp/include/qstyle.h \
		/opt/Qtopia/sharp/include/qsizepolicy.h

moc_qtprojectdialog.cpp: qtprojectdialog.h
	$(MOC) qtprojectdialog.h -o moc_qtprojectdialog.cpp

moc_qtprojectdialogbase.cpp: qtprojectdialogbase.h
	$(MOC) qtprojectdialogbase.h -o moc_qtprojectdialogbase.cpp

